branches: 
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - 
    - "@semantic-release/exec"
    - prepareCmd: ./scripts/prepare-new-version.sh ${nextRelease.version} '${JSON.stringify(commits)}'
  - "@semantic-release/changelog"
  - 
    - "@semantic-release/git"
    - assets:
      - CMakeLists.txt
      - CHANGELOG.md
      - resources/flatpak/de.gonicus.gonnect.releases.xml
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  
