name: Renovate
on:
  schedule:
    - cron: "0 1 * * *" # every night at 1 o'clock (UTC)
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.13
        with:
          token: "${{ steps.get_token.outputs.token }}"
          configurationFile: .github/renovate-config.json5